### PR TITLE
Updated further more npm packages

### PR DESCRIPTION
**Pull request by Creatune**

### CODE REVIEW

**Comment by Creatune** [comment]
The first 2 commits are useless as they got merged already. Should i create a new PR?

**Comment by srevinsaju** [comment]
Why did it come back here again?

**Comment by s-mag** [comment]
> The first 2 commits are useless as they got merged already. Should i create a new PR?

I guess you did git reset

**Comment by srevinsaju** [comment]
@Creatune 
No, I rebased it now (about this PR)
about the old change, (because you used the same branch again)

**Pull request merged**
